config system global
    set hostname "CORP-FGT-FW01"
    set timezone 12
    set admintimeout 10
    set admin-sport 8443
end

config system interface
    edit "wan1"
        set mode static
        set ip 203.0.113.3 255.255.255.0
        set allowaccess ping
        set role wan
    next
    edit "internal"
        set ip 10.0.3.1 255.255.255.0
        set allowaccess ping https ssh
        set role lan
    next
end

config firewall policy
    edit 1
        set name "Allow-LAN-to-WAN"
        set srcintf "internal"
        set dstintf "wan1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
        set utm-status enable
        set av-profile "default"
        set ips-sensor "default"
        set logtraffic all
    next
    edit 2
        set name "Deny-Inbound"
        set srcintf "wan1"
        set dstintf "internal"
        set srcaddr "all"
        set dstaddr "all"
        set action deny
        set schedule "always"
        set service "ALL"
        set logtraffic all
    next
end

config log setting
    set resolve-ip enable
end
